[project]
name = "my-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "arxiv>=2.2.0",
    "fastmcp>=2.12.3",
    "google-adk>=1.14.0",
    "litellm>=1.77.0",
]
